// Generated by scripts/gen_layer_stubs.py. Do not edit by hand.
#include "game/client/gameclient.h"
#include "game/client/components/bestclient/3d_particles.h"
#include "game/client/components/bestclient/admin_panel.h"
#include "game/client/components/bestclient/automation/automation.h"
#include "game/client/components/bestclient/bestclient.h"
#include "game/client/components/bestclient/chat_bubbles.h"
#include "game/client/components/bestclient/cherry_gifs.h"
#include "game/client/components/bestclient/cherry_gifs_cache.h"
#include "game/client/components/bestclient/clans/clans.h"
#include "game/client/components/bestclient/fast_actions.h"
#include "game/client/components/bestclient/fast_practice.h"
#include "game/client/components/bestclient/gif_bubbles.h"
#include "game/client/components/bestclient/gif_wheel.h"
#include "game/client/components/bestclient/gradient.h"
#include "game/client/components/bestclient/hookcombo.h"
#include "game/client/components/bestclient/hud_editor.h"
#include "game/client/components/bestclient/inputs.h"
#include "game/client/components/bestclient/music_player.h"
#include "game/client/components/bestclient/quick_binds.h"
#include "game/client/components/bestclient/r_jelly.h"
#include "game/client/components/bestclient/rollback_demo.h"
#include "game/client/components/bestclient/self_time_cp.h"
#include "game/client/components/bestclient/translate.h"
#include "game/client/components/bestclient/visualizer/analyzer.h"
#include "game/client/components/bestclient/visualizer/service.h"
#include "game/client/components/bestclient/visualizer/smoother.h"
#include "game/client/components/bestclient/visualizer/source.h"
#include "game/client/components/bestclient/visualizer/types.h"
#include "game/client/components/bestclient/voice/voice.h"
#include "game/client/components/menus.h"

#if !(UCLIENT_HAS_BESTCLIENT)

class CMusicPlayer::CImpl {};
void (*BCGradient_ApplyEverythingHook)(CTextCursor *pCursor, const char *pText, int Length) = nullptr;
std::unique_ptr<CRJelly> rJelly;

auto C3DParticles::OnInit() -> void
{
}

auto C3DParticles::OnReset() -> void
{
}

auto C3DParticles::OnStateChange(int NewState, int OldState) -> void
{
}

auto C3DParticles::OnRender() -> void
{
}

auto C3DParticles::ResetParticles() -> void
{
}

auto C3DParticles::RenderParticles(float ViewMinX, float ViewMaxX, float ViewMinY, float ViewMaxY, float BaseAlpha, float FadeIn, float FadeOut) -> void
{
}

CAdminPanel::CAdminPanel()
{
}

auto CAdminPanel::OnConsoleInit() -> void
{
}

auto CAdminPanel::OnReset() -> void
{
}

auto CAdminPanel::OnRelease() -> void
{
}

auto CAdminPanel::OnRender() -> void
{
}

auto CAdminPanel::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CAdminPanel::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CAdminPanel::OnRconLine(const char *pLine) -> void
{
}

auto CAdminPanel::ConToggleAdminPanel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CAdminPanel::SetActive(bool Active) -> void
{
}

auto CAdminPanel::SetUiMousePos(vec2 Pos) -> void
{
}

auto CAdminPanel::CloseActionPopup() -> void
{
}

auto CAdminPanel::OpenActionPopup(const SActionSpec &Spec, int ClientId) -> void
{
}

auto CAdminPanel::RenderPanel(const CUIRect &Screen) -> void
{
}

auto CAdminPanel::RenderRconLogin(CUIRect View) -> void
{
}

auto CAdminPanel::RenderTabs(CUIRect TabBar) -> void
{
}

auto CAdminPanel::RenderPlayersTab(CUIRect View) -> void
{
}

auto CAdminPanel::RenderPlayerActions(CUIRect View) -> void
{
}

auto CAdminPanel::RenderPlayerListAndInfo(CUIRect View) -> void
{
}

auto CAdminPanel::RenderPlayerInfo(CUIRect View, int ClientId) -> void
{
}

auto CAdminPanel::RenderTunings(CUIRect View) -> void
{
}

auto CAdminPanel::RenderLogs(CUIRect View) -> void
{
}

auto CAdminPanel::RenderActionPopup(const CUIRect &Screen) -> void
{
}

auto CAdminPanel::HasCommand(const char *pCommand, int FallbackAuth) const -> bool
{
	return bool{};
}

auto CAdminPanel::HasActionCommand(const SActionSpec &Spec) const -> bool
{
	return bool{};
}

auto CAdminPanel::IsActionEnabled(const SActionSpec &Spec, int ClientId) const -> bool
{
	return bool{};
}

auto CAdminPanel::HasPlayer(int ClientId) const -> bool
{
	return bool{};
}

auto CAdminPanel::LocalAuthLevel() const -> int
{
	return int{};
}

auto CAdminPanel::TryBuildActionCommand(char *pBuffer, int BufferSize) const -> bool
{
	return bool{};
}

auto CAutomation::OnInit() -> void
{
}

auto CAutomation::OnUpdate() -> void
{
}

auto CAutomation::OnNewSnapshot() -> void
{
}

auto CAutomation::OnStateChange(int NewState, int OldState) -> void
{
}

auto CAutomation::OnChatReceived(const SChatEvent &Event) -> void
{
}

auto CAutomation::IsAskInputActive() const -> bool
{
	return bool{};
}

auto CAutomation::AskPrompt() const -> const char *
{
	return "";
}

auto CAutomation::SubmitAskInput(const char *pText) -> void
{
}

auto CAutomation::CancelAskInput() -> void
{
}

auto CAutomation::ConShortcut(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CAutomation::IsActive() const -> bool
{
	return bool{};
}

auto CAutomation::TryReloadRules() -> void
{
}

auto CAutomation::ParseRulesFile(const char *pJson, size_t Length) -> bool
{
	return bool{};
}

auto CAutomation::EvaluateServerConnectTriggers(const NETADDR &ServerAddr) -> void
{
}

auto CAutomation::MatchesServerConnectTrigger(const SShortcut &Shortcut, const NETADDR &ServerAddr) const -> bool
{
	return bool{};
}

auto CAutomation::TargetMatchesServer(const std::string &Target, const NETADDR &ServerAddr) const -> bool
{
	return bool{};
}

auto CAutomation::OnTeamJoined(const STeamJoinEvent &Event) -> void
{
}

auto CAutomation::MatchesTeamJoinTrigger(const SShortcut &Shortcut) const -> bool
{
	return bool{};
}

auto CAutomation::SeedRunnerTeamJoinVariables(const STeamJoinEvent &Event) -> void
{
}

auto CAutomation::MatchesChatTrigger(const SShortcut &Shortcut, const SChatEvent &Event) const -> bool
{
	return bool{};
}

auto CAutomation::ChannelsMatch(EChatChannel TriggerChannel, EChatChannel EventChannel) const -> bool
{
	return bool{};
}

auto CAutomation::MatchesChatFilter(const SChatFilter &Filter, const SChatEvent &Event, bool IsMe) const -> bool
{
	return bool{};
}

auto CAutomation::MatchText(ETextMatch Match, const char *pNeedle, const char *pHaystack) const -> bool
{
	return bool{};
}

auto CAutomation::SeedRunnerChatVariables(const SChatEvent &Event) -> void
{
}

auto CAutomation::StartRunner(size_t ShortcutIndex, const SChatEvent *pChatEvent , const STeamJoinEvent *pTeamEvent) -> void
{
}

auto CAutomation::FindShortcutIndexById(const std::string &Id) const -> size_t
{
	return size_t{};
}

auto CAutomation::FindManualShortcutIndexByName(const char *pName) const -> size_t
{
	return size_t{};
}

auto CAutomation::WouldRecurseRunShortcut(const std::string &TargetId) const -> bool
{
	return bool{};
}

auto CAutomation::PushRunnerCallFrame(size_t ReturnActionIndex) -> void
{
}

auto CAutomation::PopRunnerCallFrame() -> void
{
}

auto CAutomation::FindMatchingEndIf(size_t IfIndex) const -> size_t
{
	return size_t{};
}

auto CAutomation::FindMatchingEndRepeat(size_t RepeatIndex) const -> size_t
{
	return size_t{};
}

auto CAutomation::FindOtherwise(size_t IfIndex, size_t EndIfIndex) const -> size_t
{
	return size_t{};
}

auto CAutomation::ForegroundWindowTitleValue() const -> std::string
{
	return std::string{};
}

auto CAutomation::GameWindowFocusedValue() const -> std::string
{
	return std::string{};
}

auto CAutomation::GetGamePropertyValue(const char *pProperty) const -> std::string
{
	return std::string{};
}

auto CAutomation::GetPropertyVariableName(const char *pProperty) const -> std::string
{
	return std::string{};
}

auto CAutomation::SetRunnerVariable(const char *pName, const std::string &Value) -> void
{
}

auto CAutomation::RecordTestActionOutput(size_t ActionIndex, const std::string &Value) -> void
{
}

auto CAutomation::FormatGetPlayerInfoTestResult(const SAction &Action) const -> std::string
{
	return std::string{};
}

auto CAutomation::RunnerShortcut() const -> const SShortcut *
{
	return nullptr;
}

auto CAutomation::PollTestRunRequest() -> void
{
}

auto CAutomation::ParseTestRunRequest(const char *pJson, size_t Length) -> bool
{
	return bool{};
}

auto CAutomation::WriteTestRunState(const char *pStatus) -> void
{
}

auto CAutomation::ClearTestRun() -> void
{
}

auto CAutomation::EvaluateIfCondition(const SAction &Action) const -> bool
{
	return bool{};
}

auto CAutomation::EvaluateOneIfCondition(const std::string &IfLeft, const std::string &IfOp, const std::string &IfRight, const std::string &IfLeftGet , const std::string &IfRightUnit) const -> bool
{
	return bool{};
}

auto CAutomation::ValuesMatch(const std::string &Left, const std::string &Op, const std::string &Right) const -> bool
{
	return bool{};
}

auto CAutomation::ExecuteGetAction(const SAction &Action) -> void
{
}

auto CAutomation::ExecuteGetClipboardAction(const SAction &Action) -> void
{
}

auto CAutomation::ExecuteGetPlayerInfoAction(const SAction &Action) -> void
{
}

auto CAutomation::ResolvePlayerSearchName(const SAction &Action) const -> std::string
{
	return std::string{};
}

auto CAutomation::FindClientByName(const char *pName) const -> int
{
	return int{};
}

auto CAutomation::IsPlayerInfoVariableKey(const char *pKey) const -> bool
{
	return bool{};
}

auto CAutomation::ResolvePlayerInfoVariable(const char *pKey, const char *pGet) const -> std::string
{
	return std::string{};
}

auto CAutomation::ClipboardTextValue() const -> std::string
{
	return std::string{};
}

auto CAutomation::ClipboardFileSizeValue() const -> std::string
{
	return std::string{};
}

auto CAutomation::ChatSenderPropertyValue(const char *pGet, int ClientId) const -> std::string
{
	return std::string{};
}

auto CAutomation::ExecuteTextAction(const SAction &Action) -> void
{
}

auto CAutomation::ResolveMessageValue(const SAction &Action) const -> std::string
{
	return std::string{};
}

auto CAutomation::ResolveSendChannel(const SAction &Action, EChatChannel &OutChannel) const -> bool
{
	return bool{};
}

auto CAutomation::ResolveUClientRoomId(const SAction &Action) const -> std::string
{
	return std::string{};
}

auto CAutomation::ResolveVariable(const char *pKey, const char *pGet) const -> std::string
{
	return std::string{};
}

auto CAutomation::ResolveFilterKey(const char *pKey, const SChatEvent &Event) const -> std::string
{
	return std::string{};
}

auto CAutomation::ExpandFilterText(const std::string &Template, const SChatEvent &Event) const -> std::string
{
	return std::string{};
}

auto CAutomation::ExpandTemplate(const std::string &Template) const -> std::string
{
	return std::string{};
}

auto CAutomation::StopRunner() -> void
{
}

auto CAutomation::StepRunner() -> void
{
}

auto CAutomation::ExecuteAction(const SAction &Action) -> void
{
}

auto CBestClient::UpdateSpecMoved() -> void
{
}

auto CBestClient::LoadHookComboSounds(bool LogErrors) -> void
{
}

auto CBestClient::UnloadHookComboSounds() -> void
{
}

auto CBestClient::ResetHookComboState() -> void
{
}

auto CBestClient::UpdateHookCombo() -> void
{
}

auto CBestClient::TriggerHookComboStep() -> void
{
}

auto CBestClient::HasHookComboWork() const -> bool
{
	return bool{};
}

auto CBestClient::SaveRollback() -> void
{
}

auto CBestClient::ConToggle45Degrees(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBestClient::ConToggleSmallSens(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBestClient::ConToggleDeepfly(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBestClient::ConToggleCinematicCamera(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBestClient::ConSaveRollback(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBestClient::EnsureStreamerWordsLoaded() -> void
{
}

auto CBestClient::SaveStreamerWords() const -> void
{
}

CBestClient::CBestClient()
{
}

auto CBestClient::OnInit() -> void
{
}

auto CBestClient::OnShutdown() -> void
{
}

auto CBestClient::OnReset() -> void
{
}

auto CBestClient::OnStateChange(int NewState, int OldState) -> void
{
}

auto CBestClient::OnRender() -> void
{
}

auto CBestClient::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CBestClient::OnConsoleInit() -> void
{
}

auto CBestClient::IsStreamerModeEnabled() const -> bool
{
	return bool{};
}

auto CBestClient::HasStreamerFlag(int Flag) const -> bool
{
	return bool{};
}

auto CBestClient::MaskServerAddress(const char *pAddress, char *pOutput, size_t OutputSize) const -> const char *
{
	if(pOutput && OutputSize > 0)
		str_copy(pOutput, pAddress ? pAddress : "", OutputSize);
	return pOutput;
}

auto CBestClient::IsLocalClientId(int ClientId) const -> bool
{
	return bool{};
}

auto CBestClient::ShouldHidePlayerName(int ClientId, bool InScoreboard) const -> bool
{
	return bool{};
}

auto CBestClient::AddStreamerBlockedWord(const char *pWord) -> void
{
}

auto CBestClient::RemoveStreamerBlockedWord(int Index) -> void
{
}

auto CBestClient::StreamerBlockedWords() -> const std::vector<std::string> &
{
	static const std::vector<std::string> StubValue{};
	return StubValue;
}

auto CBestClient::StreamerBlockedWordCount() -> int
{
	return int{};
}

auto CBestClient::SanitizeSensitiveCommand(const char *pInput, char *pOutput, size_t OutputSize) const -> bool
{
	if(pOutput && OutputSize > 0)
		str_copy(pOutput, pInput ? pInput : "", OutputSize);
	return false;
}

auto CBestClient::SanitizeText(const char *pInput, char *pOutput, size_t OutputSize) -> void
{
	if(pOutput && OutputSize > 0)
		str_copy(pOutput, pInput ? pInput : "", OutputSize);
}

auto CBestClient::SanitizePlayerName(const char *pInput, char *pOutput, size_t OutputSize, int ClientId, bool InScoreboard) -> void
{
	if(pOutput && OutputSize > 0)
		str_copy(pOutput, pInput ? pInput : "", OutputSize);
}

auto CBestClient::IsComponentDisabled(EBestClientComponent Component) const -> bool
{
	return bool{};
}

auto CBestClient::IsComponentDisabledByMask(int Component, int MaskLo, int MaskHi) -> bool
{
	return bool{};
}

auto CBestClient::RenderHookCombo(bool ForcePreview) -> void
{
}

auto CBestClient::RenderSpecMoved() -> void
{
}

auto CChatBubbles::Chat() const -> CChat *
{
	return nullptr;
}

auto CChatBubbles::RenderCurInput(float Y) -> void
{
}

auto CChatBubbles::RenderChatBubbles(int ClientId) -> void
{
}

auto CChatBubbles::GetOffset(int ClientId) const -> float
{
	return float{};
}

auto CChatBubbles::GetAlpha(int64_t Time) const -> float
{
	return float{};
}

auto CChatBubbles::UpdateBubbleOffsets(int ClientId, float InputBubbleHeight) -> void
{
}

auto CChatBubbles::AddBubble(int ClientId, int Team, const char *pText) -> void
{
}

auto CChatBubbles::Reset() -> void
{
}

auto CChatBubbles::LineHighlighted(int ClientId, const char *pLine) const -> bool
{
	return bool{};
}

auto CChatBubbles::BubbleRounding() const -> float
{
	return float{};
}

auto CChatBubbles::OnMessage(int MsgType, void *pRawMsg) -> void
{
}

auto CChatBubbles::OnRender() -> void
{
}

auto CChatBubbles::OnStateChange(int NewState, int OldState) -> void
{
}

auto CChatBubbles::OnWindowResize() -> void
{
}

auto CCherryGifs::ApplyFilters() -> void
{
}

auto CCherryGifs::StartListRequest(bool Reset) -> void
{
}

auto CCherryGifs::PollListRequest() -> void
{
}

auto CCherryGifs::PollThumbnails() -> void
{
}

auto CCherryGifs::ConCherryGifsTestList(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CCherryGifs::OnConsoleInit() -> void
{
}

auto CCherryGifs::OnRender() -> void
{
}

auto CCherryGifs::SetFilters(const char *pQuery, bool SortTop, bool IncludeNsfw) -> void
{
}

auto CCherryGifs::LoadMore() -> void
{
}

auto CCherryGifs::RequestThumbnail(int Index) -> void
{
}

auto CCherryGifs::TryGetNsfw(const char *pUrl, bool &OutNsfw) const -> bool
{
	return bool{};
}

auto CherryGifsCache::Load(IStorage *pStorage, const char *pGifId, std::vector<unsigned char> &vOutData) -> bool
{
	return bool{};
}

auto CherryGifsCache::Save(IStorage *pStorage, const char *pGifId, const unsigned char *pData, size_t DataSize) -> void
{
}

auto CClans::OnInit() -> void
{
}

auto CClans::OnReset() -> void
{
}

auto CClans::OnUpdate() -> void
{
}

auto CClans::OnShutdown() -> void
{
}

auto CClans::SetView(EView View) -> void
{
}

auto CClans::MarkAnnouncementsRead() -> void
{
}

auto CClans::GetUnreadCount() const -> int
{
	return int{};
}

auto CClans::OpenPreview(const char *pClanId) -> void
{
}

auto CClans::ClearPreview() -> void
{
}

auto CClans::ApplyClanTagLock(const char *pTag) -> void
{
}

auto CClans::ClearClanTagLock() -> void
{
}

auto CClans::CollectUnleashed(std::vector<SUnleashedPlayer> *pOut) const -> void
{
}

auto CClans::TryRefreshSession() -> bool
{
	return bool{};
}

auto CClans::IsMembershipCooldownActive() const -> bool
{
	return bool{};
}

auto CClans::MembershipCooldownSecondsLeft() const -> int
{
	return int{};
}

auto CClans::IsAnnounceCooldownActive() const -> bool
{
	return bool{};
}

auto CClans::AnnounceCooldownSecondsLeft() const -> int
{
	return int{};
}

auto CClans::Register(const char *pNickname, const char *pPassword) -> void
{
}

auto CClans::Login(const char *pNickname, const char *pPassword) -> void
{
}

auto CClans::Logout() -> void
{
}

auto CClans::RefreshMe() -> void
{
}

auto CClans::RefreshCatalog() -> void
{
}

auto CClans::CreateClan(const char *pName, const char *pTag, const char *pDescription, int IconId, unsigned Color, int Country, const char *pJoinPolicy, int MaxMembers) -> void
{
}

auto CClans::UpdateClanSettings(const char *pName, const char *pDescription, int IconId, unsigned Color, int Country) -> void
{
}

auto CClans::Join(const char *pClanId) -> void
{
}

auto CClans::Apply(const char *pClanId, const char *pText) -> void
{
}

auto CClans::JoinCode(const char *pCode) -> void
{
}

auto CClans::Leave() -> void
{
}

auto CClans::Disband() -> void
{
}

auto CClans::RejoinAsPresident(const char *pClanId) -> void
{
}

auto CClans::RefreshClan() -> void
{
}

auto CClans::RotateInvite() -> void
{
}

auto CClans::Promote(const char *pUserId) -> void
{
}

auto CClans::Demote(const char *pUserId) -> void
{
}

auto CClans::Kick(const char *pUserId, int BanHours) -> void
{
}

auto CClans::RefreshApplications() -> void
{
}

auto CClans::ApproveApplication(const char *pAppId) -> void
{
}

auto CClans::RejectApplication(const char *pAppId) -> void
{
}

auto CClans::RefreshAnnouncements() -> void
{
}

auto CClans::PostAnnouncement(const char *pText) -> void
{
}

auto CClans::RefreshNotifications() -> void
{
}

auto CClans::MarkNotificationRead(const char *pId) -> void
{
}

auto CClans::RefreshRecentClans() -> void
{
}

auto CClans::ClearRecentClans() -> void
{
}

auto CClans::RefreshCurrentView() -> void
{
}

auto CClans::ParseRole(const char *pRole) -> ERole
{
	return ERole{};
}

auto CClans::ResolveBaseUrl(char *pOut, int OutSize) const -> bool
{
	return bool{};
}

auto CClans::SetError(const char *pErrorCode, const char *pFallback) -> void
{
}

auto CClans::SetStatus(const char *pMsg) -> void
{
}

auto CClans::BeginRequest(std::shared_ptr<CHttpRequest> pReq, int Kind) -> void
{
}

auto CClans::BeginBackground(std::shared_ptr<CHttpRequest> pReq, int Kind) -> void
{
}

auto CClans::AuthHeader(CHttpRequest *pReq) const -> void
{
}

auto CClans::BuildSkinJson(char *pBuf, int BufSize) const -> void
{
}

auto CClans::SaveSession() const -> void
{
}

auto CClans::LoadSession() -> void
{
}

auto CClans::ClearSession() -> void
{
}

auto CClans::HandlePending() -> void
{
}

auto CClans::HandleBackground() -> void
{
}

auto CClans::ParseAuthResponse(const json_value *pRoot) -> void
{
}

auto CClans::ParseCatalog(const json_value *pRoot) -> void
{
}

auto CClans::ParseClanSnapshot(const json_value *pRoot) -> void
{
}

auto CClans::ParsePreviewSnapshot(const json_value *pRoot) -> void
{
}

auto CClans::ParseMemberSkin(const json_value *pMember, SSkin *pSkin) -> void
{
}

auto CClans::ParseApplications(const json_value *pRoot) -> void
{
}

auto CClans::ParseAnnouncements(const json_value *pRoot) -> void
{
}

auto CClans::ParseNotifications(const json_value *pRoot) -> void
{
}

auto CClans::ParseRecentClans(const json_value *pRoot) -> void
{
}

auto CClans::PushToastFromNotifications() -> void
{
}

auto CClans::IsClansUiOpen() const -> bool
{
	return bool{};
}

auto CClans::MaybePushPresence(bool UiOpen) -> void
{
}

auto CClans::MaybePollNotifications() -> void
{
}

auto CClans::MaybeAutoRefresh() -> void
{
}

auto CClans::LeaveClanLocal() -> void
{
}

auto CClans::ArmMembershipCooldown() -> void
{
}

auto CClans::GuardMembershipCooldown() -> bool
{
	return bool{};
}

auto CClans::ArmAnnounceCooldown() -> void
{
}

auto CClans::GuardAnnounceCooldown() -> bool
{
	return bool{};
}

auto CFastActions::ConOpenFa(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConAddFaLegacy(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConAddFa(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConRemoveFa(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConRemoveAllFaBinds(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConFaExecuteHover(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastActions::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

CFastActions::CFastActions()
{
}

auto CFastActions::OnReset() -> void
{
}

auto CFastActions::OnRender() -> void
{
}

auto CFastActions::OnConsoleInit() -> void
{
}

auto CFastActions::OnRelease() -> void
{
}

auto CFastActions::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CFastActions::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CFastActions::AddBind(const char *Name, const char *Command) -> void
{
}

auto CFastActions::RemoveBind(const char *Name, const char *Command) -> void
{
}

auto CFastActions::RemoveBind(int Index) -> void
{
}

auto CFastActions::RemoveAllBinds() -> void
{
}

auto CFastActions::ExecuteHoveredBind() -> void
{
}

auto CFastActions::ExecuteBind(int Bind) -> void
{
}

auto CFastPractice::CanEnable() const -> bool
{
	return bool{};
}

auto CFastPractice::Toggle() -> void
{
}

auto CFastPractice::Enable() -> void
{
}

auto CFastPractice::Disable() -> void
{
}

auto CFastPractice::ConsumeKillCommand() -> bool
{
	return bool{};
}

auto CFastPractice::ConsumePracticeChatCommand(int Team, const char *pLine) -> bool
{
	return bool{};
}

auto CFastPractice::ResetPracticeToAnchor() -> void
{
}

auto CFastPractice::PrepareInputForSend(int *pData, int Size, bool Dummy) const -> void
{
}

auto CFastPractice::OverridePredict() -> bool
{
	return bool{};
}

auto CFastPractice::ForcePredictWeapons() const -> bool
{
	return bool{};
}

auto CFastPractice::ForcePredictGrenade() const -> bool
{
	return bool{};
}

auto CFastPractice::ForcePredictGunfire() const -> bool
{
	return bool{};
}

auto CFastPractice::ForcePredictPlayers() const -> bool
{
	return bool{};
}

auto CFastPractice::InvalidateBufferedInputState() -> void
{
}

auto CFastPractice::IsPracticeParticipant(int ClientId) const -> bool
{
	return bool{};
}

auto CFastPractice::CurrentPracticeDummyId() const -> int
{
	return int{};
}

auto CFastPractice::GetLocalRaceState(SLocalRaceState &State) const -> bool
{
	return bool{};
}

auto CFastPractice::OnReset() -> void
{
}

auto CFastPractice::OnMapLoad() -> void
{
}

auto CFastPractice::OnStateChange(int NewState, int OldState) -> void
{
}

auto CFastPractice::OnNewSnapshot() -> void
{
}

auto CFastPractice::OnRender() -> void
{
}

auto CFastPractice::OnConsoleInit() -> void
{
}

auto CFastPractice::ConFastPracticeToggle(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CFastPractice::ResetPracticeState() -> void
{
}

auto CFastPractice::ResetCommandState() -> void
{
}

auto CFastPractice::ResetPracticeRaceStates() -> void
{
}

auto CFastPractice::UpdatePracticeRaceState(int ClientId, const CCharacter *pChar, int Tick) -> void
{
}

auto CFastPractice::SyncPracticeWorldConfig() -> void
{
}

auto CFastPractice::ResolveParticipantInputs(int LocalClientId, int DummyClientId, int &LocalInputConn, int &DummyInputConn) const -> bool
{
	return bool{};
}

auto CFastPractice::CurrentLocalPracticeId() const -> int
{
	return int{};
}

auto CFastPractice::ResolvePracticeRoles(int &LocalClientId, int &DummyClientId) const -> bool
{
	return bool{};
}

auto CFastPractice::UpdateGhostData() -> void
{
}

auto CFastPractice::UpdateGhostForClientId(int ClientId, SGhostData &Ghost) -> void
{
}

auto CFastPractice::ApplyVisualFastInputPrediction(int FinalTickRegular, int LocalClientId, int DummyClientId, int LocalInputConn, int DummyInputConn) -> int
{
	return int{};
}

auto CFastPractice::CaptureAnchorsFromSnapshot() -> void
{
}

auto CFastPractice::ApplyAnchorToCharacter(CGameWorld &World, const SAnchorData &Anchor) const -> bool
{
	return bool{};
}

auto CFastPractice::InitPracticeWorld() -> bool
{
	return bool{};
}

auto CFastPractice::PrunePracticeWorld(CGameWorld &World) const -> void
{
}

auto CFastPractice::ResetAttackTickHistory() -> void
{
}

auto CFastPractice::TrackFireSound(int ClientId, CCharacter *pChar) -> void
{
}

auto CFastPractice::WeaponFireSound(int Weapon) -> int
{
	return int{};
}

auto CFastPractice::MaybePlayHammerHitEffect(CCharacter *pChar) -> void
{
}

auto CFastPractice::RenderGhost(const SGhostData &Ghost, float Alpha) const -> void
{
}

auto CFastPractice::ReleaseBufferedInputState() -> void
{
}

auto CFastPractice::EchoPractice(const char *pFormat, ...) const -> void
{
}

auto CFastPractice::ParseCommandArgs(const char *pLine, std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ParseCoordinateToken(const char *pToken, float Base, float &Out) -> bool
{
	return bool{};
}

auto CFastPractice::FindClientByName(const char *pName) const -> int
{
	return int{};
}

auto CFastPractice::NormalizeCharacterAfterReset(CCharacter *pChar, bool KeepFreezeFlags) const -> void
{
}

auto CFastPractice::NormalizeWeaponSelectionInput(CCharacter *pChar) const -> void
{
}

auto CFastPractice::TeleportCharacter(CCharacter *pChar, const vec2 &Pos) const -> void
{
}

auto CFastPractice::SaveTeleportHistory(int ClientId, const vec2 &CurrentPos, const vec2 &TargetPos) -> void
{
}

auto CFastPractice::ApplyPracticeTeleport(int ClientId, CCharacter *pChar, const vec2 &TargetPos) -> void
{
}

auto CFastPractice::GivePracticeWeapon(CCharacter *pChar, int Weapon, bool Remove) const -> void
{
}

auto CFastPractice::EnsureActiveWeaponIsValid(CCharacter *pChar) const -> void
{
}

auto CFastPractice::TogglePracticeHit(CCharacter *pChar, int Weapon) const -> void
{
}

auto CFastPractice::ClampToPracticePlayableBounds(const vec2 &Pos) const -> vec2
{
	return vec2{};
}

auto CFastPractice::StoreLastTeleport(int ClientId, const vec2 &Pos) -> void
{
}

auto CFastPractice::StoreLastDeathPosition(int ClientId, const vec2 &Pos) -> void
{
}

auto CFastPractice::CaptureServerLockedTargets() -> void
{
}

auto CFastPractice::IsSafeRescueTile(int Tile) const -> bool
{
	return bool{};
}

auto CFastPractice::IsSafeRescuePosition(const vec2 &Pos, float ProximityRadius) const -> bool
{
	return bool{};
}

auto CFastPractice::TrackSafeRescuePosition(int ClientId, CCharacter *pChar) -> void
{
}

auto CFastPractice::ExecutePracticeMetaCommand(const std::string &Cmd) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeRescueCommand(int LocalClientId, CCharacter *pChar, const std::string &Cmd, const std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeTeleportCommand(int LocalClientId, CCharacter *pChar, const std::string &Cmd, const std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeStateCommand(CCharacter *pChar, const std::string &Cmd) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeWeaponCommand(CCharacter *pChar, const std::string &Cmd, const std::vector<std::string> &vArgs, bool &WeaponsMutated) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeMovementCommand(int LocalClientId, CCharacter *pChar, const std::string &Cmd, const std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeInvincibleCommand(int LocalClientId, CCharacter *pChar, const std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeCollisionCommand(CCharacter *pChar, const std::string &Cmd) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeHitOthersCommand(CCharacter *pChar, const std::vector<std::string> &vArgs) -> bool
{
	return bool{};
}

auto CFastPractice::ExecutePracticeCommand(int LocalClientId, CCharacter *pChar, const std::vector<std::string> &vArgs, bool &WeaponsMutated) -> bool
{
	return bool{};
}

auto CFastPractice::SyncPredictedWorldAfterPracticeCommand(int LocalClientId, int DummyClientId, CCharacter *pBaseChar, bool WeaponsMutated) -> void
{
}

auto CGifBubbles::OnRender() -> void
{
}

auto CGifWheel::ConAddGifWheel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CGifWheel::ConRemoveGifWheel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CGifWheel::ConRemoveAllGifWheelSlots(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CGifWheel::ConGifWheelExecuteHover(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CGifWheel::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

auto CGifWheel::EnsureThumbnail(CSlot &Slot) -> void
{
}

auto CGifWheel::PollThumbnails() -> void
{
}

CGifWheel::CGifWheel()
{
}

auto CGifWheel::OnReset() -> void
{
}

auto CGifWheel::OnRender() -> void
{
}

auto CGifWheel::OnConsoleInit() -> void
{
}

auto CGifWheel::OnRelease() -> void
{
}

auto CGifWheel::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CGifWheel::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CGifWheel::AddSlot(const char *pGifId, const char *pUrl, const char *pCaption, int EyeEmote) -> void
{
}

auto CGifWheel::RemoveSlot(int Index) -> void
{
}

auto CGifWheel::RemoveAllSlots() -> void
{
}

auto CGifWheel::SetSlotEyeEmote(int Index, int EyeEmote) -> void
{
}

auto CGifWheel::EnsureThumbnails() -> void
{
}

auto CGifWheel::ExecuteHoveredSlot() -> void
{
}

auto CGifWheel::ExecuteSlot(int Index) -> void
{
}

auto CGifWheel::Activate() -> void
{
}

auto CBcGradient::RefreshCachedText() -> void
{
}

auto CBcGradient::OnInit() -> void
{
}

auto CBcGradient::OnShutdown() -> void
{
}

auto CBcGradient::OnRender() -> void
{
}

auto CBcGradient::AnimatePhase(double GlobalTime) -> float
{
	return float{};
}

auto CBcGradient::SampleRainbow(float Hue) -> ColorRGBA
{
	return ColorRGBA{};
}

auto CBcGradient::SampleCustomGradient(float Position) -> ColorRGBA
{
	return ColorRGBA{};
}

auto CBcGradient::GetSkinToneColors(int ClientId, const CGameClient *pGameClient, ColorRGBA &Body, ColorRGBA &Feet) -> void
{
}

auto CBcGradient::GetAnimatedEndpointColors(int ClientId, const CGameClient *pGameClient, float Phase, ColorRGBA &Color1, ColorRGBA &Color2) -> void
{
}

auto CBcGradient::BuildStaticColorSplits(const char *pText, const ColorRGBA &Color1, const ColorRGBA &Color2) -> std::vector<STextColorSplit>
{
	return std::vector<STextColorSplit>{};
}

auto CBcGradient::BuildAnimatedColorSplits(const char *pText, const ColorRGBA &Color1, const ColorRGBA &Color2, float Phase) -> std::vector<STextColorSplit>
{
	return std::vector<STextColorSplit>{};
}

auto CBcGradient::BuildAnimatedTextSplits(const char *pText, int ClientId, CGameClient *pGameClient, float Phase) -> std::vector<STextColorSplit>
{
	return std::vector<STextColorSplit>{};
}

auto CBcGradient::ApplyEverythingGradient(CTextCursor *pCursor, const char *pText, int Length, CGameClient *pGameClient) -> void
{
}

auto CHookCombo::LoadSounds(bool LogErrors) -> void
{
}

auto CHookCombo::UnloadSounds() -> void
{
}

auto CHookCombo::ResetState() -> void
{
}

auto CHookCombo::TriggerStep() -> void
{
}

auto CHookCombo::HasWork() const -> bool
{
	return bool{};
}

auto CHookCombo::OnInit() -> void
{
}

auto CHookCombo::OnShutdown() -> void
{
}

auto CHookCombo::OnReset() -> void
{
}

auto CHookCombo::OnStateChange(int NewState, int OldState) -> void
{
}

auto CHookCombo::OnRender() -> void
{
}

auto CHookCombo::Render(bool ForcePreview) -> void
{
}

auto CHudEditor::OnConsoleInit() -> void
{
}

auto CHudEditor::OnRender() -> void
{
}

auto CHudEditor::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CHudEditor::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CHudEditor::OnStateChange(int NewState, int OldState) -> void
{
}

auto CHudEditor::Activate() -> void
{
}

auto CHudEditor::Deactivate() -> void
{
}

auto CHudEditor::PopupModuleSettings(void *pContext, CUIRect View, bool Active) -> CUi::EPopupMenuFunctionResult
{
	return CUi::EPopupMenuFunctionResult{};
}

auto CHudEditor::GetModuleVisual(HudLayout::EModule Module) const -> SModuleVisual
{
	return SModuleVisual{};
}

auto CHudEditor::GetFallbackModuleRect(HudLayout::EModule Module) const -> CUIRect
{
	return CUIRect{};
}

auto CHudEditor::HudWidth() const -> float
{
	return float{};
}

auto CHudEditor::HudHeight() const -> float
{
	return float{};
}

auto CHudEditor::IsEditableModule(HudLayout::EModule Module) const -> bool
{
	return bool{};
}

auto CHudEditor::IsModuleEnabled(HudLayout::EModule Module) const -> bool
{
	return bool{};
}

auto CHudEditor::RenderModulePreview(const SModuleVisual &Visual) const -> void
{
}

auto CHudEditor::CollectModuleVisuals(SModuleVisual *pOut, int &Count) const -> void
{
}

auto CHudEditor::HitTestModule(vec2 MousePos) const -> HudLayout::EModule
{
	return HudLayout::EModule{};
}

auto CHudEditor::HitTestResizeHandle(vec2 MousePos, int &OutCorner) const -> HudLayout::EModule
{
	return HudLayout::EModule{};
}

auto CHudEditor::UpdateDragging(vec2 MousePos) -> void
{
}

auto CHudEditor::UpdateResizing(vec2 MousePos) -> void
{
}

auto CHudEditor::StartResetAnimation(HudLayout::EModule Module, int Kind) -> void
{
}

auto CHudEditor::CancelResetAnimation(HudLayout::EModule Module) -> void
{
}

auto CHudEditor::FindOrAddResetAnim(HudLayout::EModule Module) -> SResetAnim *
{
	return nullptr;
}

auto CHudEditor::UpdateResetAnimation() -> void
{
}

auto CHudEditor::RenderOverlay(vec2 MousePos) -> void
{
}

auto CHudEditor::RenderModuleOutline(const SModuleVisual &Visual, bool Hovered, bool Selected) const -> void
{
}

auto CHudEditor::RenderResizeHandles(const SModuleVisual &Visual) const -> void
{
}

auto CHudEditor::RenderClosingPopupFrame() const -> void
{
}

auto CHudEditor::RenderModuleLabel(const SModuleVisual &Visual) const -> void
{
}

auto CHudEditor::OpenModuleSettings(const SModuleVisual &Visual) -> void
{
}

auto CHudEditor::ApplyDraggedPosition(HudLayout::EModule Module, const CUIRect &Rect) -> void
{
}

auto CHudEditor::SnapRect(const CUIRect &Rect, HudLayout::EModule DraggedModule) const -> CUIRect
{
	return CUIRect{};
}

auto BcInputs::EffectiveOffsetTicks() -> float
{
	return float{};
}

auto BcInputs::PredictionTicks(float OffsetTicks) -> int
{
	return int{};
}

auto BcInputs::PredictionTicksOthers(float OffsetTicks) -> int
{
	return int{};
}

auto BcInputs::ApplyOffset(float OffsetTicks, int &Tick, float &Intra) -> void
{
}

auto BcInputs::BestInterpolationAmount(float Fraction, float DeltaLength, bool Enable) -> float
{
	(void)DeltaLength;
	(void)Enable;
	return Fraction;
}

auto BcInputs::BestInterpolate(vec2 PrevPos, vec2 CurPos, float Fraction, bool Enable) -> vec2
{
	(void)Enable;
	return mix(PrevPos, CurPos, Fraction);
}

auto BcInputs::BestInterpolate(float PrevPos, float CurPos, float Fraction, bool Enable) -> float
{
	(void)Enable;
	return mix(PrevPos, CurPos, Fraction);
}

auto BcInputs::FastOthers() -> bool
{
	return bool{};
}

auto BcInputs::BestOthers() -> bool
{
	return bool{};
}

auto BcInputs::SaikoOthers() -> bool
{
	return bool{};
}

auto BcInputs::DeltaOthers() -> bool
{
	return bool{};
}

auto BcInputs::FOthers() -> bool
{
	return bool{};
}

auto BcInputs::AnyOthers() -> bool
{
	return bool{};
}

auto BcInputs::ImmediateOthers() -> bool
{
	return bool{};
}

CMusicPlayer::CMusicPlayer()
{
}

CMusicPlayer::~CMusicPlayer()
{
}

auto CMusicPlayer::OnReset() -> void
{
}

auto CMusicPlayer::OnUpdate() -> void
{
}

auto CMusicPlayer::OnRender() -> void
{
}

auto CMusicPlayer::OnShutdown() -> void
{
}

auto CMusicPlayer::OnWindowResize() -> void
{
}

auto CMusicPlayer::HudReservation() const -> SHudReservation
{
	return SHudReservation{};
}

auto CMusicPlayer::GetHudPushOffsetForRect(const CUIRect &Rect, float CanvasWidth, float Padding) const -> float
{
	return float{};
}

auto CMusicPlayer::GetHudPushDownOffsetForRect(const CUIRect &Rect, float CanvasHeight, float Padding) const -> float
{
	return float{};
}

auto CMusicPlayer::GetNowPlayingInfo(SNowPlayingInfo &Out) const -> bool
{
	return bool{};
}

auto CMusicPlayer::GetHudThemeColor(ColorRGBA &Out, bool ForcePreview) const -> bool
{
	return bool{};
}

auto CMusicPlayer::GetHudEditorRect(bool ForcePreview) const -> CUIRect
{
	return CUIRect{};
}

auto CMusicPlayer::RenderHudEditor(bool ForcePreview) -> void
{
}

auto CMusicPlayer::RenderMusicPlayer(bool ForcePreview) -> void
{
}

auto CMusicPlayer::EnsureImpl() -> void
{
}

auto CQuickBinds::ConToggle45Degrees(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CQuickBinds::ConToggleSmallSens(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CQuickBinds::ConToggleDeepfly(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CQuickBinds::OnConsoleInit() -> void
{
}

CRJelly::CRJelly(CGameClient *pClient)
{
}

auto CRJelly::Reset() -> void
{
}

auto CRJelly::GetDeform(int ClientId, vec2 PrevVel, vec2 Vel, vec2 LookDir, bool InAir, bool WantOtherDir, float DeltaTime, vec2 ExtraDeformImpulse , float ExtraCompression) -> JellyTee
{
	return JellyTee{};
}

auto CRJelly::IsEnabledFor(int ClientId) const -> bool
{
	return bool{};
}

auto CRJelly::StateFor(int ClientId) -> CState *
{
	return nullptr;
}

auto CRollbackDemo::ConSaveRollback(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CRollbackDemo::SaveRollback() -> void
{
}

auto CRollbackDemo::OnConsoleInit() -> void
{
}

auto CSelfTimeCp::ConPlace(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CSelfTimeCp::ConClear(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CSelfTimeCp::ConUndo(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CSelfTimeCp::Clear(bool Echo) -> void
{
}

auto CSelfTimeCp::UndoLast(bool Echo) -> void
{
}

auto CSelfTimeCp::Place() -> void
{
}

auto CSelfTimeCp::ResetCurrentRun(int RaceTick) -> void
{
}

auto CSelfTimeCp::UpdateTouches() -> void
{
}

auto CSelfTimeCp::CommitBestFromRun() -> void
{
}

auto CSelfTimeCp::SyncBestFinishFromRecord() -> void
{
}

auto CSelfTimeCp::ApplyServerBest(int TimeCpIndex, float BestTime) -> void
{
}

auto CSelfTimeCp::HasValidBest(float BestTime) const -> bool
{
	return bool{};
}

auto CSelfTimeCp::TrySeedBestFromGhost(SCheckpoint &Checkpoint) -> bool
{
	return bool{};
}

auto CSelfTimeCp::TrySeedBestFromServer(SCheckpoint &Checkpoint) -> bool
{
	return bool{};
}

auto CSelfTimeCp::FindNearestTimeCpIndex(int TileX) const -> int
{
	return int{};
}

auto CSelfTimeCp::DetectTimeCpHit(vec2 PrevPos, vec2 Pos) const -> int
{
	return int{};
}

auto CSelfTimeCp::KnownPersonalBestSeconds() const -> float
{
	return float{};
}

auto CSelfTimeCp::AlignedRaceTimeSeconds() const -> float
{
	return float{};
}

auto CSelfTimeCp::IsGapBoundary(int TileX, int TileY) const -> bool
{
	return bool{};
}

auto CSelfTimeCp::FindGap(int TileX, int PreferTileY, int &TileYTop, int &TileYBottom) const -> bool
{
	return bool{};
}

auto CSelfTimeCp::IsTouchingCheckpoint(const SCheckpoint &Checkpoint, vec2 PrevPos, vec2 Pos) const -> bool
{
	return bool{};
}

auto CSelfTimeCp::CurrentRaceTimeSeconds() const -> float
{
	return float{};
}

auto CSelfTimeCp::CurrentRaceStartTick() const -> int
{
	return int{};
}

auto CSelfTimeCp::PlacementPos() const -> vec2
{
	return vec2{};
}

auto CSelfTimeCp::Enabled() const -> bool
{
	return bool{};
}

auto CSelfTimeCp::CanPlace() const -> bool
{
	return bool{};
}

auto CSelfTimeCp::OnConsoleInit() -> void
{
}

auto CSelfTimeCp::OnReset() -> void
{
}

auto CSelfTimeCp::OnStateChange(int NewState, int OldState) -> void
{
}

auto CSelfTimeCp::OnUpdate() -> void
{
}

auto CSelfTimeCp::OnRender() -> void
{
}

auto CSelfTimeCp::OnMessage(int MsgType, void *pRawMsg) -> void
{
}

auto ITranslateBackend::EncodeSource(const char *pSource) const -> const char *
{
	return "";
}

auto ITranslateBackend::EncodeTarget(const char *pTarget) const -> const char *
{
	return "";
}

auto CTranslate::ConTranslate(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTranslate::ConTranslateId(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTranslate::ConToggleTranslate(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTranslate::CreateBackend(const char *pText, const char *pSourceLanguage, const char *pTargetLanguage) const -> std::unique_ptr<ITranslateBackend>
{
	return std::unique_ptr<ITranslateBackend>{};
}

auto CTranslate::IncomingSourceLanguage() const -> const char *
{
	return "";
}

auto CTranslate::IncomingTargetLanguage() const -> const char *
{
	return "";
}

auto CTranslate::OutgoingSourceLanguage() const -> const char *
{
	return "";
}

auto CTranslate::OutgoingTargetLanguage() const -> const char *
{
	return "";
}

auto CTranslate::IsIgnoredIncomingLanguage(const char *pLanguage) const -> bool
{
	return bool{};
}

auto CTranslate::ShouldTranslateOutgoingChat(const char *pText) const -> bool
{
	return bool{};
}

auto CTranslate::HasPendingJobs() const -> bool
{
	return bool{};
}

auto CTranslate::CanStartRequest() const -> bool
{
	return bool{};
}

auto CTranslate::TranslateLine(CChat::CLine &Line, bool ShowProgress, bool RespectIgnoredIncomingLanguages) -> void
{
}

auto CTranslate::IsIncomingChatTranslationCandidate(const CChat::CLine &Line) -> bool
{
	return bool{};
}

auto CTranslate::IsLocalIncomingChatLine(const CChat::CLine &Line) const -> bool
{
	return bool{};
}

auto CTranslate::OnConsoleInit() -> void
{
}

auto CTranslate::OnRender() -> void
{
}

auto CTranslate::Translate(int Id, bool ShowProgress) -> void
{
}

auto CTranslate::Translate(const char *pName, bool ShowProgress) -> void
{
}

auto CTranslate::Translate(CChat::CLine &Line, bool ShowProgress) -> void
{
}

auto CTranslate::TryTranslateOutgoingChat(int Team, const char *pText) -> bool
{
	return bool{};
}

auto CTranslate::AutoTranslate(CChat::CLine &Line) -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::RebuildPlan() -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::BuildWindows() -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::BuildTwiddles(int FftSize, std::vector<std::complex<float>> &vTwiddles, std::vector<int> &vBitReverse) -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::ComputeBandDistribution() -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::CopyLatestSamples(float *pDst, int Count) const -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::RunFft(std::vector<std::complex<float>> &vBuffer, const std::vector<std::complex<float>> &vTwiddles, const std::vector<int> &vBitReverse) const -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::ResolveMainFftSize(int SampleRate) -> int
{
	return int{};
}

BestClientVisualizer::CVisualizerAnalyzer::CVisualizerAnalyzer()
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::Configure(const SVisualizerConfig &Config) -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::PushMonoSamples(const float *pSamples, int NumSamples) -> void
{
}

auto BestClientVisualizer::CVisualizerAnalyzer::Analyze(SVisualizerFrame &OutFrame) -> void
{
}

auto BestClientVisualizer::BuildRenderBars(const SVisualizerFrame &Frame, float *pOutBars, int RequestedBarCount) -> void
{
}

auto BestClientVisualizer::CRealtimeMusicVisualizer::RefreshConfig() -> void
{
}

BestClientVisualizer::CRealtimeMusicVisualizer::CRealtimeMusicVisualizer()
{
}

BestClientVisualizer::CRealtimeMusicVisualizer::~CRealtimeMusicVisualizer()
{
}

auto BestClientVisualizer::CRealtimeMusicVisualizer::SetPlaybackHint(const SVisualizerPlaybackHint &Hint) -> void
{
}

auto BestClientVisualizer::CRealtimeMusicVisualizer::PollFrame(SVisualizerFrame &OutFrame) -> bool
{
	return bool{};
}

BestClientVisualizer::CVisualizerSmoother::CVisualizerSmoother()
{
}

auto BestClientVisualizer::CVisualizerSmoother::Configure(const SVisualizerConfig &Config) -> void
{
}

auto BestClientVisualizer::CVisualizerSmoother::Process(const SVisualizerFrame &RawFrame, SVisualizerFrame &OutFrame) -> void
{
}

auto BestClientVisualizer::CreatePulseVisualizerSource() -> std::unique_ptr<IVisualizerSource>
{
	return std::unique_ptr<IVisualizerSource>{};
}

auto BestClientVisualizer::CreateWasapiVisualizerSource() -> std::unique_ptr<IVisualizerSource>
{
	return std::unique_ptr<IVisualizerSource>{};
}

auto BestClientVisualizer::CreatePassiveVisualizerSource() -> std::unique_ptr<IVisualizerSource>
{
	return std::unique_ptr<IVisualizerSource>{};
}

auto BestClientVisualizer::VisualizerBackendStatusName(EVisualizerBackendStatus Status) -> const char *
{
	return "";
}

auto CVoiceChat::VoiceModAuth(const char *pKey) -> void
{
}

auto CVoiceChat::OnConsoleInit() -> void
{
}

auto CVoiceChat::OnReset() -> void
{
}

auto CVoiceChat::OnStateChange(int NewState, int OldState) -> void
{
}

auto CVoiceChat::OnUpdate() -> void
{
}

auto CVoiceChat::OnRelease() -> void
{
}

auto CVoiceChat::OnRender() -> void
{
}

auto CVoiceChat::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CVoiceChat::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CVoiceChat::OnShutdown() -> void
{
}

auto CVoiceChat::IsClientTalking(int ClientId) const -> bool
{
	return bool{};
}

auto CVoiceChat::GetClientVolumePercent(int ClientId) const -> std::optional<int>
{
	return std::optional<int>{};
}

auto CVoiceChat::SetClientVolumePercent(int ClientId, int VolumePercent) -> void
{
}

auto CVoiceChat::RenderHudTalkingIndicator(float HudWidth, float HudHeight, bool ForcePreview) -> void
{
}

auto CVoiceChat::RenderHudMuteStatusIndicator(float HudWidth, float HudHeight, bool ForcePreview) -> void
{
}

auto CVoiceChat::GetHudTalkingIndicatorRect(float HudWidth, float HudHeight, bool ForcePreview) const -> CUIRect
{
	return CUIRect{};
}

auto CVoiceChat::GetHudMuteStatusIndicatorRect(float HudWidth, float HudHeight, bool ForcePreview) const -> CUIRect
{
	return CUIRect{};
}

auto CVoiceChat::RenderMenuPanel(const CUIRect &View) -> void
{
}

auto CVoiceChat::RenderMenuSettingsBlock(const CUIRect &View, float RevealPhase) -> void
{
}

auto CVoiceChat::GetMenuSettingsBlockHeight(float RevealPhase) const -> float
{
	return float{};
}

auto CVoiceChat::RenderMenuControlBinds(const CUIRect &View) -> void
{
}

auto CVoiceChat::RenderMenuPanelToggleBind(const CUIRect &View) -> void
{
}

auto CVoiceChat::TryHandleChatCommand(const char *pLine) -> bool
{
	return bool{};
}

auto CVoiceChat::RequestSoundboardDeleteConfirm(int Index) -> void
{
}

auto CVoiceChat::ConfirmSoundboardDelete() -> void
{
}

auto CVoiceChat::CancelSoundboardDelete() -> void
{
}

auto CVoiceChat::StartVoice() -> void
{
}

auto CVoiceChat::StopVoice() -> void
{
}

auto CVoiceChat::ShouldStartVoicePipeline(bool Online) const -> bool
{
	return bool{};
}

auto CVoiceChat::ShouldKeepVoicePipelineActive() const -> bool
{
	return bool{};
}

auto CVoiceChat::ShouldUseSecondaryTeamConnection() const -> bool
{
	return bool{};
}

auto CVoiceChat::HasPendingPlaybackAudio() const -> bool
{
	return bool{};
}

auto CVoiceChat::HasRecentVoiceActivity(int64_t Now) const -> bool
{
	return bool{};
}

auto CVoiceChat::OpenNetworking() -> bool
{
	return bool{};
}

auto CVoiceChat::OpenSecondaryNetworking() -> bool
{
	return bool{};
}

auto CVoiceChat::CloseNetworking() -> void
{
}

auto CVoiceChat::CloseSecondaryNetworking() -> void
{
}

auto CVoiceChat::OpenAudioDevices() -> bool
{
	return bool{};
}

auto CVoiceChat::CloseAudioDevices() -> void
{
}

auto CVoiceChat::CreateEncoder() -> bool
{
	return bool{};
}

auto CVoiceChat::DestroyEncoder() -> void
{
}

auto CVoiceChat::TuneEncoderForNetwork() -> void
{
}

auto CVoiceChat::ClearPeerState() -> void
{
}

auto CVoiceChat::SendHello() -> void
{
}

auto CVoiceChat::SendHelloSecondary() -> void
{
}

auto CVoiceChat::SendHelloResponse(NETSOCKET Socket, const uint8_t *pNonce, const std::vector<uint8_t> &vHelloPayload) -> void
{
}

auto CVoiceChat::SendGoodbye() -> void
{
}

auto CVoiceChat::SendGoodbyeSecondary() -> void
{
}

auto CVoiceChat::SendVoiceFrame(const uint8_t *pOpusData, int OpusSize, int Team, vec2 Position) -> void
{
}

auto CVoiceChat::SendVoiceFrameSecondary(const uint8_t *pOpusData, int OpusSize, int Team, vec2 Position) -> void
{
}

auto CVoiceChat::ProcessNetwork() -> void
{
}

auto CVoiceChat::ProcessSecondaryNetwork() -> void
{
}

auto CVoiceChat::ProcessVoiceRelayPacket(const uint8_t *pRawData, int DataSize, int Offset, uint16_t SelfVoiceId) -> void
{
}

auto CVoiceChat::ProcessServerListPing() -> void
{
}

auto CVoiceChat::ProcessCapture() -> void
{
}

auto CVoiceChat::ProcessPlayback() -> void
{
}

auto CVoiceChat::CleanupPeers() -> void
{
}

auto CVoiceChat::ShouldTransmit() const -> bool
{
	return bool{};
}

auto CVoiceChat::IsInGameOnlyBlocked() const -> bool
{
	return bool{};
}

auto CVoiceChat::LocalTeam() const -> int
{
	return int{};
}

auto CVoiceChat::LocalVoiceTeam() const -> int
{
	return int{};
}

auto CVoiceChat::LocalOwnVoiceTeam() const -> int
{
	return int{};
}

auto CVoiceChat::IsUseTeam0Mode() const -> bool
{
	return bool{};
}

auto CVoiceChat::IsEnableYourGroupMode() const -> bool
{
	return bool{};
}

auto CVoiceChat::IsVoiceTeamAudible(int Team) const -> bool
{
	return bool{};
}

auto CVoiceChat::IsUcTeamOverrideMode() const -> bool
{
	return bool{};
}

auto CVoiceChat::UcTargetVoiceTeam() const -> int
{
	return int{};
}

auto CVoiceChat::IsUcIncludeOwnTeamMode() const -> bool
{
	return bool{};
}

auto CVoiceChat::LocalPosition() const -> vec2
{
	return vec2{};
}

auto CVoiceChat::CurrentRoomKey() const -> std::string
{
	return std::string{};
}

auto CVoiceChat::LocalGameClientId() const -> int
{
	return int{};
}

auto CVoiceChat::BeginReconnect() -> void
{
}

auto CVoiceChat::InvalidatePeerCaches(bool MappingDirty , bool TalkingDirty) -> void
{
}

auto CVoiceChat::RefreshPeerCaches() -> void
{
}

auto CVoiceChat::RefreshPeerMappingCache() -> void
{
}

auto CVoiceChat::RefreshTalkingCache() -> void
{
}

auto CVoiceChat::ResolvePeerClientId(const CRemotePeer &Peer) const -> int
{
	return int{};
}

auto CVoiceChat::ShouldShowPeerInMembers(const CRemotePeer &Peer) const -> bool
{
	return bool{};
}

auto CVoiceChat::ComputePeerGain(const CRemotePeer &Peer) const -> float
{
	return float{};
}

auto CVoiceChat::IsRadiusFilterEnabled() const -> bool
{
	return bool{};
}

auto CVoiceChat::RadiusFilterDistanceUnits() const -> float
{
	return float{};
}

auto CVoiceChat::IsPositionWithinRadiusFilter(vec2 Position) const -> bool
{
	return bool{};
}

auto CVoiceChat::SetPanelActive(bool Active) -> void
{
}

auto CVoiceChat::SetSoundboardPanelActive(bool Active) -> void
{
}

auto CVoiceChat::SetUiMousePos(vec2 Pos) -> void
{
}

auto CVoiceChat::RenderPanel(const CUIRect &Screen, bool ShowCloseButton) -> void
{
}

auto CVoiceChat::RenderSoundboardPanel(const CUIRect &Screen) -> void
{
}

auto CVoiceChat::RenderServersSection(CUIRect View) -> void
{
}

auto CVoiceChat::RenderMembersSection(CUIRect View) -> void
{
}

auto CVoiceChat::RenderSettingsSection(CUIRect View) -> void
{
}

auto CVoiceChat::SortedPeerIds() const -> std::vector<uint16_t>
{
	return std::vector<uint16_t>{};
}

auto CVoiceChat::FetchServerList() -> void
{
}

auto CVoiceChat::FinishServerList() -> void
{
}

auto CVoiceChat::ResetServerListTask() -> void
{
}

auto CVoiceChat::FetchSoundboardList() -> void
{
}

auto CVoiceChat::FinishSoundboardList() -> void
{
}

auto CVoiceChat::ReloadLocalVoiceRecordItems() -> void
{
}

auto CVoiceChat::StartSoundboardItemDownload(int Index) -> void
{
}

auto CVoiceChat::StartSoundboardItemDelete(int Index) -> void
{
}

auto CVoiceChat::TickSoundboardDelete() -> void
{
}

auto CVoiceChat::TickSoundboard() -> void
{
}

auto CVoiceChat::PlaySoundboardItem(int Index, bool SendToVoice) -> void
{
}

auto CVoiceChat::StopSoundboard() -> void
{
}

auto CVoiceChat::ProcessSoundboardVoiceInject() -> void
{
}

auto CVoiceChat::IsSoundboardItemPlaying(int ItemIndex) const -> bool
{
	return bool{};
}

auto CVoiceChat::StartSoundboardUpload() -> void
{
}

auto CVoiceChat::TickSoundboardUpload() -> void
{
}

auto CVoiceChat::TryDecodeWav(const uint8_t *pData, int DataSize, int NativeSampleRate, int NativeChannels, std::vector<int16_t> &vPcmOut) -> bool
{
	return bool{};
}

auto CVoiceChat::ArmVoiceRecord(int ClientId) -> void
{
}

auto CVoiceChat::CancelVoiceRecord(bool Notify) -> void
{
}

auto CVoiceChat::TickVoiceRecord() -> void
{
}

auto CVoiceChat::AppendVoiceRecordSamples(int ClientId, const int16_t *pSamples, size_t SampleCount) -> void
{
}

auto CVoiceChat::FinalizeVoiceRecord() -> void
{
}

auto CVoiceChat::SaveVoiceRecordWav(const std::vector<int16_t> &vPcm, const char *pPlayerName, int ClientId, char *pOutTitle, int TitleSize) -> bool
{
	return bool{};
}

auto CVoiceChat::DeleteLocalVoiceRecordItem(int Index) -> void
{
}

auto CVoiceChat::StartServerListPings() -> void
{
}

auto CVoiceChat::CloseServerListPingSocket() -> void
{
}

auto CVoiceChat::LoadMutedNamesFromFile() -> void
{
}

auto CVoiceChat::SaveMutedNamesToFile() -> void
{
}

auto CVoiceChat::EffectiveServerAddress() const -> std::string
{
	return std::string{};
}

auto CVoiceChat::EffectiveServerLabel() const -> const char *
{
	return "";
}

auto CVoiceChat::IsManagedServerConfig() const -> bool
{
	return bool{};
}

auto CVoiceChat::CurrentHelloAuthTimestamp() const -> uint64_t
{
	return uint64_t{};
}

auto CVoiceChat::AppendHelloAuthProof(std::vector<uint8_t> &vPacket) const -> void
{
}

auto CVoiceChat::SendModAuthReq() -> void
{
}

auto CVoiceChat::SendModPlayerListReq() -> void
{
}

auto CVoiceChat::SendModMuteReq(uint16_t SessionId, bool Mute) -> void
{
}

auto CVoiceChat::RenderModSection(CUIRect View) -> void
{
}

auto CVoiceChat::ConVoiceConnect(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConVoiceDisconnect(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConVoiceStatus(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConToggleVoicePanel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConKeyVoiceTalk(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConToggleVoiceMicMute(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConToggleVoiceHeadphonesMute(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConToggleVoiceSoundboardPanel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConRecordVoice(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CVoiceChat::ConRecordVoiceStop(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CMenus::AssetsEditorClearAssets() -> void
{
}

auto CMenus::AssetsEditorReloadAssets() -> void
{
}

auto CMenus::AssetsEditorReloadAssetsImagesOnly() -> void
{
}

auto CMenus::AssetsEditorResetPartSlots() -> void
{
}

auto CMenus::AssetsEditorEnsureDefaultExportNames() -> void
{
}

auto CMenus::AssetsEditorSyncExportNameFromType() -> void
{
}

auto CMenus::AssetsEditorCommitExportNameForType() -> void
{
}

auto CMenus::AssetsEditorValidateRequiredSlotsForType(int Type) -> void
{
}

auto CMenus::AssetsEditorBuildFamilyKey(int Type, const CDataSprite *pSprite, char *pOut, int OutSize) -> void
{
}

auto CMenus::AssetsEditorCopyRectScaledNearest(CImageInfo &Dst, const CImageInfo &Src, int DstX, int DstY, int DstW, int DstH, int SrcX, int SrcY, int SrcW, int SrcH) -> bool
{
	return bool{};
}

auto CMenus::AssetsEditorComposeImage(CImageInfo &OutputImage) -> bool
{
	return bool{};
}

auto CMenus::AssetsEditorExport() -> bool
{
	return bool{};
}

auto CMenus::AssetsEditorCancelDrag() -> void
{
}

auto CMenus::AssetsEditorRequestClose() -> void
{
}

auto CMenus::AssetsEditorCloseNow() -> void
{
}

auto CMenus::AssetsEditorRenderExitConfirm(const CUIRect &Rect) -> void
{
}

auto CMenus::AssetsEditorCollectHoveredCandidates(const CUIRect &Rect, int Type, const std::vector<SAssetsEditorPartSlot> &vSlots, vec2 Mouse, std::vector<int> &vOutCandidates) const -> void
{
}

auto CMenus::AssetsEditorResolveHoveredSlotWithCycle(const CUIRect &Rect, int Type, const std::vector<SAssetsEditorPartSlot> &vSlots, vec2 Mouse, bool ClickedLmb, int PreferredSlotIndex) -> int
{
	return int{};
}

auto CMenus::AssetsEditorApplyDrop(int TargetSlotIndex, const char *pDonorName, int SourceSlotIndex, bool ApplyAllSameSize) -> void
{
}

auto CMenus::AssetsEditorUpdatePreviewIfDirty() -> void
{
}

auto CMenus::AssetsEditorRenderCanvas(const CUIRect &Rect, IGraphics::CTextureHandle Texture, int W, int H, int Type, bool ShowGrid, int HighlightSlot) -> void
{
}

auto CMenus::RenderAssetsEditorScreen(CUIRect MainView) -> void
{
}

#else
static const int gs_UClientBestClientLayerStubAnchor = 1;
#endif
