// Generated by scripts/gen_layer_stubs.py. Do not edit by hand.
#include "game/client/gameclient.h"
#include "game/client/components/tclient/bg_draw.h"
#include "game/client/components/tclient/bg_draw_file.h"
#include "game/client/components/tclient/bindchat.h"
#include "game/client/components/tclient/bindwheel.h"
#include "game/client/components/tclient/custom_communities.h"
#include "game/client/components/tclient/mod.h"
#include "game/client/components/tclient/moving_tiles.h"
#include "game/client/components/tclient/mumble.h"
#include "game/client/components/tclient/outlines.h"
#include "game/client/components/tclient/pet.h"
#include "game/client/components/tclient/player_indicator.h"
#include "game/client/components/tclient/rainbow.h"
#include "game/client/components/tclient/scripting/impl.h"
#include "game/client/components/tclient/scripting.h"
#include "game/client/components/tclient/skinprofiles.h"
#include "game/client/components/tclient/statusbar.h"
#include "game/client/components/tclient/tclient.h"
#include "game/client/components/tclient/trails.h"
#include "game/client/components/tclient/warlist.h"
#include "game/client/components/menus.h"

#if !(UCLIENT_HAS_TCLIENT)

auto CBgDraw::ConBgDraw(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBgDraw::ConBgDrawErase(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBgDraw::ConBgDrawReset(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBgDraw::ConBgDrawSave(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBgDraw::ConBgDrawLoad(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBgDraw::Reset() -> void
{
}

auto CBgDraw::Save(const char *pFile, bool Verbose) -> bool
{
	return bool{};
}

auto CBgDraw::Load(const char *pFile, bool Verbose) -> bool
{
	return bool{};
}

auto CBgDraw::MakeSpaceFor(int Count) -> void
{
}

auto CBgDraw::OnConsoleInit() -> void
{
}

auto CBgDraw::OnRender() -> void
{
}

auto CBgDraw::OnStateChange(int NewState, int OldState) -> void
{
}

auto CBgDraw::OnMapLoad() -> void
{
}

auto CBgDraw::OnShutdown() -> void
{
}

CBgDraw::CBgDraw()
{
}

CBgDraw::~CBgDraw()
{
}

auto BgDrawFile::Write(const std::function<bool(const char *)> &WriteLine, const CBgDrawItemData &Data) -> bool
{
	return bool{};
}

auto BgDrawFile::Read(const std::function<bool(char *pBuf, int Length)> &ReadLine, CBgDrawItemData &Data) -> bool
{
	return bool{};
}

auto BgDrawFile::Write(FILE *pFile, const CBgDrawItemData &Data) -> bool
{
	return bool{};
}

auto BgDrawFile::Read(FILE *pFile, CBgDrawItemData &Data) -> bool
{
	return bool{};
}

CBindChat::CBind::CBind(const char *pName, const char *pCommand)
{
}

auto CBindChat::CBind::CompContent(const CBind &Other) const -> bool
{
	return bool{};
}

auto CBindChat::ConAddBindchat(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindChat::ConBindchats(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindChat::ConRemoveBindchat(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindChat::ConRemoveBindchatAll(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindChat::ConBindchatDefaults(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindChat::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

auto CBindChat::ExecuteBind(const CBind &Bind, const char *pArgs) -> void
{
}

CBindChat::CBindChat()
{
}

auto CBindChat::OnConsoleInit() -> void
{
}

auto CBindChat::AddBind(const CBind &Bind) -> void
{
}

auto CBindChat::RemoveBind(const char *pName) -> bool
{
	return bool{};
}

auto CBindChat::RemoveAllBinds() -> void
{
}

auto CBindChat::GetBind(const char *pCommand) -> CBind *
{
	return nullptr;
}

auto CBindChat::CheckBindChat(const char *pText) -> bool
{
	return bool{};
}

auto CBindChat::ChatDoBinds(const char *pText) -> bool
{
	return bool{};
}

auto CBindChat::ChatDoAutocomplete(bool ShiftPressed) -> bool
{
	return bool{};
}

auto CBindWheel::ConOpenBindwheel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConAddBindwheelLegacy(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConAddBindwheel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConRemoveBindwheel(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConRemoveAllBindwheelBinds(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConBindwheelExecuteHover(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CBindWheel::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

CBindWheel::CBindWheel()
{
}

auto CBindWheel::OnReset() -> void
{
}

auto CBindWheel::OnRender() -> void
{
}

auto CBindWheel::OnConsoleInit() -> void
{
}

auto CBindWheel::OnRelease() -> void
{
}

auto CBindWheel::OnCursorMove(float x, float y, IInput::ECursorType CursorType) -> bool
{
	return bool{};
}

auto CBindWheel::OnInput(const IInput::CEvent &Event) -> bool
{
	return bool{};
}

auto CBindWheel::AddBind(const char *Name, const char *Command) -> void
{
}

auto CBindWheel::RemoveBind(const char *Name, const char *Command) -> void
{
}

auto CBindWheel::RemoveBind(int Index) -> void
{
}

auto CBindWheel::RemoveAllBinds() -> void
{
}

auto CBindWheel::ExecuteHoveredBind() -> void
{
}

auto CBindWheel::ExecuteBind(int Bind) -> void
{
}

auto CCustomCommunities::DownloadCustomCommunitiesDDNetInfo() -> void
{
}

auto CCustomCommunities::LoadCustomCommunitiesDDNetInfo() -> void
{
}

auto CCustomCommunities::OnInit() -> void
{
}

auto CCustomCommunities::OnConsoleInit() -> void
{
}

auto CCustomCommunities::OnRender() -> void
{
}

CCustomCommunities::~CCustomCommunities()
{
}

auto CMod::ModWeapon(int Id) -> void
{
}

auto CMod::OnFire(bool Pressed) -> void
{
}

auto CMod::OnConsoleInit() -> void
{
}

auto CMod::OnRender() -> void
{
}

auto CMod::OnStateChange(int OldState, int NewState) -> void
{
}

auto CMovingTiles::Reset() -> void
{
}

auto CMovingTiles::OnStateChange(int NewState, int OldState) -> void
{
}

auto CMovingTiles::OnMapLoad() -> void
{
}

auto CMovingTiles::OnRender() -> void
{
}

auto CMumble::MakeContext() -> void
{
}

CMumble::CMumble()
{
}

CMumble::~CMumble()
{
}

auto CMumble::OnRender() -> void
{
}

auto CMumble::OnConsoleInit() -> void
{
}

auto COutlines::OnMapLoad() -> void
{
}

auto COutlines::OnRender() -> void
{
}

auto CPet::OnRender() -> void
{
}

auto CPet::OnMapLoad() -> void
{
}

auto CPlayerIndicator::OnRender() -> void
{
}

auto CRainbow::OnRender() -> void
{
}

auto CScriptingCtx::Implementation() -> const char *
{
	return "";
}

CScriptingCtx::CScriptingCtx()
{
}

CScriptingCtx::~CScriptingCtx()
{
}

auto CScriptingCtx::Run(IStorage *pStorage, const char *pFilename, const char *pArgs) -> void
{
}

auto CScripting::ConExecScript(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CScripting::ExecScript(const char *pFilename, const char *pArgs) -> void
{
}

auto CScripting::OnConsoleInit() -> void
{
}

CProfile::CProfile(int BodyColor, int FeetColor, int CountryFlag, int Emote, const char *pSkinName, const char *pName, const char *pClan,
		const char *pAssetEntities , const char *pAssetGame , const char *pAssetParticles ,
		const char *pAssetHud , const char *pAssetExtras , const char *pAssetCursor , const char *pAssetArrow)
{
}

auto CSkinProfiles::ConAddProfile(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CSkinProfiles::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

auto CSkinProfiles::AddProfile(int BodyColor, int FeetColor, int CountryFlag, int Emote, const char *pSkinName, const char *pName, const char *pClan,
		const char *pAssetEntities , const char *pAssetGame , const char *pAssetParticles ,
		const char *pAssetHud , const char *pAssetExtras , const char *pAssetCursor , const char *pAssetArrow) -> void
{
}

auto CSkinProfiles::ApplyProfile(int Dummy, const CProfile &Profile) -> void
{
}

auto CSkinProfiles::OnConsoleInit() -> void
{
}

CStatusItem::CStatusItem(std::function<void()> Render, std::function<float()> Width, const char *pLetters, const char *pName, const char *pDisplayName, const char *pDesc, bool ShowLabel)
{
}

auto CStatusBar::OnRender() -> void
{
}

auto CStatusBar::OnInit() -> void
{
}

auto CStatusBar::UpdateStatusBarSize() -> void
{
}

auto CStatusBar::ApplyStatusBarScheme(const char *pScheme) -> void
{
}

auto CStatusBar::UpdateStatusBarScheme(char *pScheme) -> void
{
}

auto CStatusBar::GetDurationWidth(int Duration) -> float
{
	return float{};
}

auto CStatusBar::GetDigitsIndex(int Value, int Max) -> int
{
	return int{};
}

auto CStatusBar::AngleWidth() -> float
{
	return float{};
}

auto CStatusBar::AngleRender() -> void
{
}

auto CStatusBar::PingWidth() -> float
{
	return float{};
}

auto CStatusBar::PingRender() -> void
{
}

auto CStatusBar::PredictionWidth() -> float
{
	return float{};
}

auto CStatusBar::PredictionRender() -> void
{
}

auto CStatusBar::PositionWidth() -> float
{
	return float{};
}

auto CStatusBar::PositionRender() -> void
{
}

auto CStatusBar::LocalTimeWidth() -> float
{
	return float{};
}

auto CStatusBar::LocalTimeRender() -> void
{
}

auto CStatusBar::RaceTimeWidth() -> float
{
	return float{};
}

auto CStatusBar::RaceTimeRender() -> void
{
}

auto CStatusBar::FPSWidth() -> float
{
	return float{};
}

auto CStatusBar::FPSRender() -> void
{
}

auto CStatusBar::VelocityWidth() -> float
{
	return float{};
}

auto CStatusBar::VelocityRender() -> void
{
}

auto CStatusBar::ZoomWidth() -> float
{
	return float{};
}

auto CStatusBar::ZoomRender() -> void
{
}

auto CStatusBar::SpaceWidth() -> float
{
	return float{};
}

auto CStatusBar::SpaceRender() -> void
{
}

auto CStatusBar::LabelRender(const char *pLabel) -> void
{
}

auto CStatusBar::LabelWidth(const char *pLabel) -> float
{
	return float{};
}

auto CTClient::AirRescue() -> void
{
}

auto CTClient::ConAirRescue(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTClient::ConCalc(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTClient::ConRandomTee(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTClient::ConchainRandomColor(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData) -> void
{
}

auto CTClient::RandomBodyColor() -> void
{
}

auto CTClient::RandomFeetColor() -> void
{
}

auto CTClient::RandomSkin(void *pUserData) -> void
{
}

auto CTClient::RandomFlag(void *pUserData) -> void
{
}

auto CTClient::ConSpecId(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTClient::SpecId(int ClientId) -> void
{
}

auto CTClient::ConEmoteCycle(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CTClient::SendNonDuplicateMessage(int Team, const char *pLine) -> bool
{
	return bool{};
}

auto CTClient::DoFinishCheck() -> void
{
}

auto CTClient::ServerCommandExists(const char *pCommand) -> bool
{
	return bool{};
}

CTClient::CTClient()
{
}

auto CTClient::OnInit() -> void
{
}

auto CTClient::OnMessage(int MsgType, void *pRawMsg) -> void
{
}

auto CTClient::OnConsoleInit() -> void
{
}

auto CTClient::OnRender() -> void
{
}

auto CTClient::OnStateChange(int OldState, int NewState) -> void
{
}

auto CTClient::OnNewSnapshot() -> void
{
}

auto CTClient::SetForcedAspect() -> void
{
}

auto CTClient::FetchTClientInfo() -> void
{
}

auto CTClient::FinishTClientInfo() -> void
{
}

auto CTClient::ResetTClientInfoTask() -> void
{
}

auto CTClient::NeedUpdate() -> bool
{
	return bool{};
}

auto CTClient::RenderMiniVoteHud() -> void
{
}

auto CTClient::RenderCenterLines() -> void
{
}

auto CTClient::RenderCtfFlag(vec2 Pos, float Alpha) -> void
{
}

auto CTClient::ChatDoSpecId(const char *pInput) -> bool
{
	return bool{};
}

auto CTrails::OnRender() -> void
{
}

auto CTrails::OnReset() -> void
{
}

auto CTrails::ClearAllHistory() -> void
{
}

auto CTrails::ClearHistory(int ClientId) -> void
{
}

auto CTrails::ShouldPredictPlayer(int ClientId) -> bool
{
	return bool{};
}

auto CWarList::ConNameIndex(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConClanIndex(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveNameIndex(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveClanIndex(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConNameTeam(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConClanTeam(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveNameWar(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveNameTeam(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveClanWar(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveClanTeam(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConName(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConClan(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveName(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConRemoveClan(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConAddWarEntry(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConUpsertWarType(IConsole::IResult *pResult, void *pUserData) -> void
{
}

auto CWarList::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData) -> void
{
}

CWarList::CWarList()
{
}

CWarList::~CWarList()
{
}

auto CWarList::OnNewSnapshot() -> void
{
}

auto CWarList::OnConsoleInit() -> void
{
}

auto CWarList::UpdateWarPlayers() -> void
{
}

auto CWarList::UpdateWarEntry(int Index, const char *pName, const char *pClan, const char *pReason, CWarType *pType) -> void
{
}

auto CWarList::UpsertWarType(int Index, const char *pType, ColorRGBA Color, bool UseGradient , ColorRGBA Color2) -> void
{
}

auto CWarList::AddWarEntryInGame(int WarType, const char *pName, const char *pReason, bool IsClan) -> void
{
}

auto CWarList::RemoveWarEntryInGame(int WarType, const char *pName, bool IsClan) -> void
{
}

auto CWarList::AddWarEntry(const char *pName, const char *pClan, const char *pReason, const char *pType) -> void
{
}

auto CWarList::AddWarType(const char *pType, ColorRGBA Color, bool UseGradient , ColorRGBA Color2) -> void
{
}

auto CWarList::RemoveWarEntry(const char *pName, const char *pClan, const char *pType) -> void
{
}

auto CWarList::RemoveWarType(const char *pType) -> void
{
}

auto CWarList::RemoveWarEntryDuplicates(const char *pName, const char *pClan) -> void
{
}

auto CWarList::RemoveWarEntry(CWarEntry *Entry) -> void
{
}

auto CWarList::RemoveWarEntry(int Index) -> void
{
}

auto CWarList::RemoveWarType(int Index) -> void
{
}

auto CWarList::GetPriorityColor(int ClientId) -> ColorRGBA
{
	return ColorRGBA{};
}

auto CWarList::GetNameplateColor(int ClientId) -> ColorRGBA
{
	return ColorRGBA{};
}

auto CWarList::GetClanColor(int ClientId) -> ColorRGBA
{
	return ColorRGBA{};
}

auto CWarList::BuildGradientColorSplits(const char *pText, const ColorRGBA &Color1, const ColorRGBA &Color2) -> std::vector<STextColorSplit>
{
	return std::vector<STextColorSplit>{};
}

auto CWarList::BuildAnimatedGradientColorSplits(const char *pText, const ColorRGBA &Color1, const ColorRGBA &Color2, float Phase) -> std::vector<STextColorSplit>
{
	return std::vector<STextColorSplit>{};
}

auto CWarList::GetAnyWar(int ClientId) -> bool
{
	return bool{};
}

auto CWarList::GetNameWar(int ClientId) -> bool
{
	return bool{};
}

auto CWarList::GetClanWar(int ClientId) -> bool
{
	return bool{};
}

auto CWarList::GetReason(char *pReason, int ClientId) -> void
{
}

auto CWarList::GetWarData(int ClientId) -> CWarDataCache &
{
	static CWarDataCache StubValue{};
	return StubValue;
}

auto CWarList::SortWarEntries() -> void
{
}

auto CWarList::FindWarType(const char *pType) -> CWarType *
{
	return nullptr;
}

auto CWarList::FindWarEntry(const char *pName, const char *pClan, const char *pType) -> CWarEntry *
{
	return nullptr;
}

auto CMenus::DoLine_KeyReader(CUIRect &View, CButtonContainer &ReaderButton, CButtonContainer &ClearButton, const char *pName, const char *pCommand) -> bool
{
	return bool{};
}

auto CMenus::DoSliderWithScaledValue(const void *pId, int *pOption, const CUIRect *pRect, const char *pStr, int Min, int Max, int Scale, const IScrollbarScale *pScale, unsigned Flags, const char *pSuffix) -> bool
{
	return bool{};
}

auto CMenus::DoEditBoxWithLabel(CLineInput *LineInput, const CUIRect *pRect, const char *pLabel, const char *pDefault, char *pBuf, size_t BufSize) -> bool
{
	return bool{};
}

auto CMenus::DoButtonLineSize_Menu(CButtonContainer *pButtonContainer, const char *pText, int Checked, const CUIRect *pRect, float ButtonLineSize, bool Fake, const char *pImageName, int Corners, float Rounding, float FontFactor, ColorRGBA Color) -> int
{
	return int{};
}

auto CMenus::RenderDevSkin(vec2 RenderPos, float Size, const char *pSkinName, const char *pBackupSkin, bool CustomColors, int FeetColor, int BodyColor, int Emote, bool Rainbow, bool Cute, ColorRGBA ColorFeet, ColorRGBA ColorBody) -> void
{
}

auto CMenus::RenderTeeCute(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, bool CuteEyes, float Alpha) -> void
{
}

auto CMenus::RenderFontIcon(const CUIRect Rect, const char *pText, float Size, int Align) -> void
{
}

auto CMenus::DoButtonNoRect_FontIcon(CButtonContainer *pButtonContainer, const char *pText, int Checked, const CUIRect *pRect, int Corners) -> int
{
	return int{};
}

auto CMenus::PopupConfirmRemoveWarType() -> void
{
}

auto CMenus::RenderSettingsTClient(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientSettings(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientBindWheel(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientChatBinds(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientWarList(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientStatusBar(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientInfo(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientProfiles(CUIRect MainView) -> void
{
}

auto CMenus::RenderSettingsTClientConfigs(CUIRect MainView) -> void
{
}

#else
static const int gs_UClientTClientLayerStubAnchor = 1;
#endif
